services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_PB_URL=https://pb.evhsync.com
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studyvault.rule=Host(`study.evhsync.com`)"
      - "traefik.http.routers.studyvault.tls=true"
      - "traefik.http.routers.studyvault.tls.certresolver=letsencrypt"
      - "traefik.http.services.studyvault.loadbalancer.server.port=80"